<?php

/**
 * @file
 * Contains entityreference_rendered_widget.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function entityreference_rendered_widget_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the entityreference_rendered_widget module.
    case 'help.page.entityreference_rendered_widget':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Implements widget for Rendered Display in Entity Reference') . '</p>';
      return $output;

    default:
  }
}
