<?php
/**
 * @file
 * Entityreference Custom Display module.
 */

/**
 * Implements hook_entity_info_alter().
 */
function entityreference_custom_display_entity_info_alter(&$info) {
  foreach ($info as $entity_type => $data) {
    $info[$entity_type]['view modes']['entityreference_custom_display'] = array(
      'label' => t('Entity Custom Display'),
      'custom settings' => TRUE,
    );
  }
}

/**
 * Implements hook_field_widget_info().
 */
function entityreference_custom_display_field_widget_info() {
  $widgets['custom_display'] = array(
    'label' => t('Custom display'),
    'description' => t('An custon widget for entityreference'),
    'field types' => array('entityreference'),
    'settings' => array(
      'custom_display_fields' => array(),
    ),
    'behaviors' => array(
      'multiple values' => FIELD_BEHAVIOR_CUSTOM,
      'default value' => FIELD_BEHAVIOR_NONE,
    ),
  );

  return $widgets;
}

/**
 * Implements hook_field_widget_settings_form().
 */
function entityreference_custom_display_field_widget_settings_form($field, $instance) {
  $widget = $instance['widget'];
  $settings = $widget['settings'];

  if ($widget['type'] == 'custom_display') {
    $target_type = $field['settings']['target_type'];

    // Get all view modes in entity type.
    $entity_info = entity_get_info($target_type);
    $view_modes = array_keys($entity_info['view modes']);

    $element['custom_display_fields'] = array(
      '#type' => 'select',
      '#title' => t('View mode displayed'),
      '#options' => drupal_map_assoc($view_modes),
      '#default_value' => isset($settings['custom_display_fields']) ? $settings['custom_display_fields'] : array(),
    );

    return $element;
  }
}

/**
 * Implements hook_field_widget_form().
 */
function entityreference_custom_display_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {

  $widget = $instance['widget'];

  if ($widget['type'] == 'custom_display') {
    $element['#type'] = 'item';
    // Custom validate function.
    $element['#element_validate'][] = 'entityreference_custom_display_validate';
    $entity_type = $instance['entity_type'];
    $handler = entityreference_get_selection_handler($field, $instance);
    $view_mode = $widget['settings']['custom_display_fields'];

    // Get all Referenceables Entities.
    $all_entities = $handler->getReferencableEntities();

    // Build the path of the element.
    $parents_path = $field['field_name'];

    if (!empty($form['#parents'])) {
      $parents = $form['#parents'];
      $first_parent = array_shift($parents);
      $parents_path = $first_parent;

      if (!empty($parents)) {
        $parents_path .= '[' . implode('][', $parents) . ']';
      }
      $parents_path .= '[' . $field['field_name'] . ']';
    }

    // Get attached checkboxes in node.
    $attach = entityreference_custom_display_attach_fields($entity_type, $parents_path, $field, $langcode, $view_mode, $items, $all_entities);

    if (empty($attach)) {
      // Bundle of entity.
      $bundle = $instance['bundle'];
      // Markup if no have results.
      $element[] = array(
        '#type' => 'markup',
        '#markup' => t('There are entities of type @type and bundle @bundle', array('@type' => $entity_type, '@bundle' => $bundle)),
      );
      return $element;
    }
    // Attach checkboxes in element.
    $element += $attach;
  }
  return $element;
}

/**
 * Return attached checkboxes.
 *
 * @param string $entity_type
 *   String containing the type of entity.
 * @param string $parents_path
 *   String parents_path.
 * @param array $field
 *   Array contains field.
 * @param string $langcode
 *   String language.
 * @param array $items
 *   (Optional) Array of all marked items.
 * @param array $all_entities
 *   (Optional) Array containing all entities.
 *
 * @return array
 *   Array to be added to Element.
 */
function entityreference_custom_display_attach_fields($entity_type, $parents_path, array $field, $langcode, $view_mode, array $items = array(), array $all_entities = array()) {

  // Define empty array.
  $rows = array();

  $delta = 0;
  foreach ($all_entities as $ids) {
    $ids = array_keys($ids);
    // Load entities.
    $entities = entity_load($entity_type, $ids);
    foreach ($entities as $entity_id => $entity) {
      $label = entity_label($entity_type, $entity);
      $name = $parents_path . '[' . $langcode . '][0]';
      $frontend_id = 'edit-' . $parents_path . '-' . $langcode . '-' . $delta;;

      $entity_view = entity_view($entity_type, array($entity), $view_mode);
      $type = 'radio';

      if ($field['cardinality'] != 1) {
        // Change type.
        $type = 'checkbox';
        $name = $parents_path . '[' . $langcode . '][' . $delta . ']';
      }

      $suffix = '<div class="view-mode" data-for="' . $frontend_id . '">';
      $suffix .= drupal_render($entity_view) . '</div>';

      $rows[$delta] = array(
        'target_id' => array(
          '#type' => $type,
          '#delta' => $delta,
          '#return_value' => $entity_id,
          '#default_value' => entityreference_custom_display_checkbox_default_value($entity_id, $items),
          '#field_suffix' => '<label class="option" for="' . $frontend_id . '">' . $label . '</label>',
          '#title_display' => 'after',
          '#suffix' => $suffix,
          '#name' => $name . '[target_id]',
          '#attributes' => array(
            'id' => $frontend_id,
          ),
        ),
      );

      ++$delta;
    }
  }
  return $rows;
}

/**
 * Get Default values of items.
 *
 * @param array $items
 *   (Optional) Saved items.
 *
 * @return array
 *   Default values.
 */
function entityreference_custom_display_default_values(array $items = array()) {
  $default_values = array();
  foreach ($items as $record) {
    $default_values[] = $record['target_id'];
  }
  return drupal_map_assoc($default_values);
}

/**
 * Return default value of checkbox.
 *
 * @param int $entity_id
 *   Id of current items.
 * @param array $items
 *   (Optional) Saved items.
 *
 * @return int
 *   Default value or 0 if empty.
 */
function entityreference_custom_display_checkbox_default_value($entity_id, array $items = array()) {
  $default_values = entityreference_custom_display_default_values($items);
  if (in_array($entity_id, $default_values)) {
    return $entity_id;
  }
  return 0;
}

/**
 * Validate checkboxes elements.
 */
function entityreference_custom_display_validate($element, &$form_state, $form) {
  array_pop($element['#parents']);
  $input = drupal_array_get_nested_value($form_state['values'], $element['#parents']);
  $langcode = $element['#language'];
  $field_name = $element['#field_name'];
  $field = $form_state['field'][$field_name][$langcode]['field'];

  if ($field['cardinality'] == 1) {
    $input[$langcode] = array($input[$langcode][0]);
    form_set_value($element, $input, $form_state);
  }
  else {
    // Initial value.
    $empty = TRUE;
    foreach ($input[$langcode] as $key => $values) {
      if (!empty($values['target_id'])) {
        $empty = FALSE;
      }
      else {
        unset($input[$langcode][$key]);
      }
    }

    // Verify if required field.
    if ($element['#required']) {
      // Message if field is empty.
      if ($empty) {
        $array_error = array('@field' => $element['#title']);
        form_set_error($element['#field_name'], t('@field is required.', $array_error));
      }
    }
    if (!$empty) {
      form_set_value($element, $input, $form_state);
    }
  }
}
